Doc/plano qualidade
fga-eps-mds/2023.2-Dnit-DOC pull request #61
Opened 2023-10-11 18:57 UTC by RafaelBP02

---
name: Pull Request 
about: Criação de Pull Request
---

Issue relacionada: resolves #43 

### Descrição 
Escrita do documento entregável plano de qualidade

2023-10-16 18:33 UTC, thiagohdaqw requested changes
Bom trabalho, rafael. Encontrei alguns erros e sugeri algumas modificações

2023-10-16 18:33 UTC, thiagohdaqw commented on docs/plano-monitoramento/plano-qualidade.md
> +
```suggestion
**Testes automatizados**: Além da análise estática, a equipe utilizou testes automatizados, incluindo testes unitários e de integração, que atuam atuam durante o desenvolvimento e nas revisões de Pull Requests, para auxiliar no gerenciamento do projeto. Essa abordagem permite a equipe não apenas verificar os cenários planejados, mas também identificar e lidar com situações de erro indesejados.
```

2023-10-16 18:33 UTC, thiagohdaqw commented on docs/plano-monitoramento/plano-qualidade.md
> +|11/10/2023| Adição de métricas de qualidade | Rafael|
```suggestion
|11/10/2023| Adição de métricas de qualidade | Rafael|
|16/10/2023| Revisão e correção ortográfica | Thiago |

```

2023-10-16 18:33 UTC, thiagohdaqw commented on docs/plano-monitoramento/plano-qualidade.md
> +|Vunrelabilidades|Classificado como "A" no SonarCloud|
```suggestion
|Vulnerabilidades|Classificado como "A" no SonarCloud|
```

2023-10-16 18:33 UTC, thiagohdaqw commented on docs/plano-monitoramento/plano-qualidade.md
> +As métricas de projeto, processo e produto de software são instrumentos quantitativos essenciais para avaliar a eficiência dos processos de software e dos projetos que empregam esses processos. Estas
Acho que ficaria melhor colocando esse paragrafo 
`As métricas de projeto, processo e produto de software são instrumentos quantitativos essenciais para avaliar a eficiência dos processos de software e dos projetos que empregam esses processos. Estas métricas oferecem insights objetivos, auxiliando engenheiros de software na análise e melhoria contínua da qualidade, eficiência e eficácia dos softwares. Uma métrica eficaz deve ser fácil de entender e calcular, fornecer resultados não ambíguos e estar fundamentada no modelo de requisitos, projeto ou estrutura do programa, independente das características específicas das linguagens de programação.` Antes da tabela

2023-10-16 18:33 UTC, thiagohdaqw commented on docs/plano-monitoramento/plano-qualidade.md
> +|Duplicação|Até 3.0% de duplicação de código|
pq 3%?

2023-10-19 21:14 UTC, RafaelBP02 commented on docs/plano-monitoramento/plano-qualidade.md
> +|Duplicação|Até 3.0% de duplicação de código|
Eu mantive a mesma porcentagem do grupo do semestre passado

2023-10-20 00:42 UTC, thiagohdaqw commented on docs/plano-monitoramento/plano-qualidade.md
> +|Duplicação|Até 3.0% de duplicação de código|
Em time que está ganhando, não se mexe

2023-10-20 00:43 UTC, thiagohdaqw approved these changes
[![aaaaa](https://images.squarespace-cdn.com/content/v1/574faff6f8baf35e5da43485/1495284929670-UWO1P40E52N649BBVSNS/rocket_3.gif)]

2023-10-22 13:13 UTC, merged